# Generated by Django 5.1.2 on 2024-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_by_card',
            field=models.BooleanField(default=False, verbose_name='Payment by card'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In processing', max_length=50, verbose_name='Order status'),
        ),
    ]
