# Generated by Django 5.1.2 on 2024-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_by_card',
            field=models.BooleanField(default=True, verbose_name='Payment by card'),
        ),
    ]
