# Generated by Django 5.1.2 on 2024-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_sizes_remove_products_quantity_remove_products_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Brand'),
        ),
    ]
