# Generated by Django 5.1.2 on 2024-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['brand'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Discount, %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
