# Generated by Django 5.1.2 on 2024-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_products_options_alter_products_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Size'),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
