# Generated by Django 5.1.2 on 2024-11-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_productsizes_size_delete_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Size')),
            ],
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='clothes.sizes', verbose_name='Size'),
        ),
    ]
