# Generated by Django 5.1.2 on 2024-11-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_sizes_alter_productsizes_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizes',
            old_name='name',
            new_name='size',
        ),
    ]
