# Generated by Django 5.1.2 on 2024-11-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_rename_name_sizes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.sizes', verbose_name='Size'),
        ),
    ]
