# Generated by Django 5.1.2 on 2024-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_available_sizes_alter_cart_size'),
        ('clothes', '0009_alter_productsizes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Size'),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
