# Generated by Django 5.1.2 on 2024-11-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_sizes_alter_productsizes_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterModelTable(
            name='sizes',
            table='size',
        ),
    ]
