# Generated by Django 5.1.2 on 2024-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('clothes', '0007_sizes_alter_productsizes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='available_sizes',
            field=models.ManyToManyField(to='clothes.sizes', verbose_name='Available Sizes'),
        ),
    ]
