# Generated by Django 5.1.2 on 2024-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_available_sizes_alter_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='available_sizes',
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=7, verbose_name='Size'),
        ),
    ]
